### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by yrashk** [pjungwir/aggs_for_arrays#5]
Hi Paul,

I am preparing to package your extensions on [postgres.pm](http://postgres.pm) – would it be possible to tag releases in this repo? This makes it so much easier to pick up releases automatically.

**Comment by pjungwir** [comment]
Oh yes, I should be doing that. I tagged the last few versions. Let me know if you need more.

**Comment by yrashk** [comment]
Thanks! Looks like agg_for_vecs got tags, but not this repo yet

**Comment by pjungwir** [comment]
I see tags. Can you look again?

**Comment by yrashk** [comment]
Can see them now. Maybe github ui was lagging to show these when I checked
first.

Thank you!
